"""add sources to chats

Revision ID: e023c8e6d3d1
Revises: eb953925a7ab
Create Date: 2026-10-03 20:21:04.432595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e023c8e6d3d1'
down_revision: Union[str, Sequence[str], None] = 'eb953925a7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('sources', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'sources')
    # ### end Alembic commands ###
