"""add file path to papers

Revision ID: f883c34d4ec4
Revises: 5d4b61df4023
Create Date: 2026-10-01 23:50:15.629069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f883c34d4ec4'
down_revision: Union[str, Sequence[str], None] = '5d4b61df4023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('file_path', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'file_path')
    # ### end Alembic commands ###
